appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kbPnbN9MLrIbmrIM6lS4JD5X6dk7FiguYW5GGoXlFVeOVOfV1Eijte73DnAp0PBR9Mh7zB66Es04OESAemvoB9RKt318mgOZuq9zKllgU4DLfQVJoknrxW5EClfuMEpfxnbii7YIhKXfOKeSEVw4wDFWwcodwftgqrWi5df47wPpFSuZDCv1bWIQPxIV97nY2+w+lheTGClQjvLZVSpe0DJ3DQym9aDpSMaGxBi3Fy0ts3TRYWufZT9jORptbWV7DJ7iGWJEVSEtBn9Cy1ZvL+GHWhtVgeSEovvK/xNE4sz4jxAbfhKGVdn9mbUpfcNjG/Lm4Lq4CoBbNnMLrMs+Z8sHkazkqPJUvMaxt63hT9FPAqeUUN3HGH6k6KcGlAEc/A0VE5grP23e38LMK8/Ul+wqALVRxAJuzx4k2pHv6aeBro/Mag8yZrAhM9R++2mtrbuJEIY3j46/NfX9TbL4TAFyKVzMfH+9NC4tL2CSEZBzB0+iXv2n6LxNf0tm3WXAwz5hdV6xlnvtrxQ392J4IC6ZWgx7rR7L+948V4WQK//2nEpiLl3SJ03lJGhJiq7aZIhD9YStSIDeNXMzeefCfF2yx/bBOE5hO8Y6bVE1WjBRcSNJg9yCVHzUaEtvBMZk+LWPAXOVd8f1LNpy22r2T0NVZgk1dQF/dJwHMxnds+o=}
