travis:
  secure:
    BINSTAR_TOKEN: Un/nYthP/xTFEvLpNrPs7j/6CfPjnZsN4jlyP7XNYaT8JJDmUzyGgortMfHwWBaoaFuSdxtHs3Q8eFbj/lSQorIQJqomV1yL4HsZEO3bI3iIrgiWXZKHE9d3UO2PPdL0jtV7FX+Fk1vMz6FGMDNEoZRCNGCyt8Dsaq4ukjyswmYzfQBwd/4v/1e9zAfpSy6Lm1ij6mKA2O5+lbf+OP3XnnVEozUuFfco3SuX7Nx9UwoaNzTUN11hpudKvglwBe9xdrONXAoZg8WfQ96E4Ao0sBFF661P7MJjFM/Vwd9VgHlRwe/uoKjD/p7+ZMqKaaJUevN4Te/SlTrjRztrk/CL9C0cy40TzN3vQvenF6mUyqmCBvEqZipd02dkL2CLmW8U66nHL70EJX60YInoLokm/QX11uenkrJEzWdd4p6Z0hLquwh9uzPjh6Iyyo+uD6ZAhG6GqovNi+V/sfs/M/woj8yby60nnP8b1PlA+mSgOclptAqYv3DFHzAyMI1+iIb6h8JlyA+R+hK+Mf+aFHBR+6MnOfTJ1ryYiuKiceTS4A5d37AjYqTdx8m2GjOTcg62Kwv7cB+XGjDf0xKrlIdC9GQ5ECPv1WcwryT6iZnSq0MZUFjWIxew8NTRuWPIL5wSdZejvwdG7y1PcIgcYdhz7T2VWBM096BSstDEjuyD3Tw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
